---

- name: Install network tools
  pacman:
    name: '{{ network_packages }}'
    state: present

- name: Enable DHCP service
  ansible.builtin.service: name=dhcpcd state=started enabled=true

- name: Enable NetworkManager service
  ansible.builtin.service: name=NetworkManager state=started enabled=true
